name: Build and Upload Executable

on:
  schedule:
    - cron: '0 0 * * 0'  # Uruchomienie automatyczne raz w tygodniu (niedziela o północy)
  push:
    branches:
      - Task1
      - Task2
      - Task3
      - Task4
      - Task5
      - Task6
      - Task7  # Uruchomienie po push na odpowiednie gałęzie
  workflow_dispatch:  # Ręczne uruchomienie przez użytkownika

jobs:
  build:
    runs-on: windows-latest  # Domyślny serwer Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Wybierz wersję Pythona

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller  # Dodaj instalację pyinstaller
          .\installResources.ps1

      - name: List files in working directory
        run: dir

      - name: Find and build main.py
        run: |
          $paths = @(
            "./Task1/main.py",
            "./Task2/main.py",
            "./Task3/main.py",
            "./Task4/main.py",
            "./Task5/main.py",
            "./Task6/main.py",
            "./Task7/main.py"
          )
          $mainPath = $paths | Where-Object { Test-Path $_ }
          if ($mainPath) {
            pyinstaller --onefile $mainPath
          } else {
            Write-Error "main.py not found in expected paths"
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: dist/*.exe  # Ścieżka do pliku .exe

