name: Build and Upload Executable

on:
  schedule:
    - cron: '0 0 * * 0'  # Uruchomienie automatyczne raz w tygodniu (niedziela o północy)
  push:
    branches:
      - Task1
      - Task2
      - Task3
      - Task4
      - Task5
      - Task6
      - Task7  # Uruchomienie po push na odpowiednie gałęzie
  workflow_dispatch:  # Ręczne uruchomienie przez użytkownika

jobs:
  build:
    runs-on: windows-latest  # Domyślny serwer Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pobierz wszystkie gałęzie

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Wybierz wersję Pythona

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller  # Dodaj instalację pyinstaller
          .\installResources.ps1

      - name: Build main.py if it exists
        run: |
          $branches = @("Task1", "Task2", "Task3", "Task4", "Task5", "Task6", "Task7")
          $branchWithMain = $null

          foreach ($branch in $branches) {
            git checkout $branch
            if (Test-Path -Path ./main.py) {
              $branchWithMain = $branch
              break
            }
          }

          if ($branchWithMain) {
            pyinstaller --onefile main.py
          } else {
            Write-Error "main.py not found in any branch"
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: dist/*.exe  # Ścieżka do pliku .exe
