name: Build and Upload Executable

on:
  schedule:
    - cron: '0 0 * * 0'  # Uruchomienie automatyczne raz w tygodniu (niedziela o północy)
  push:
    branches:
      - Task0
      - Task1
      - Task2
      - Task3
      - Task4
      - Task5
      - Task6
      - Task7  # Uruchomienie po push na odpowiednie gałęzie
  workflow_dispatch:  # Ręczne uruchomienie przez użytkownika

jobs:
  build:
    runs-on: windows-latest  # Domyślny serwer Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller  # Dodaj instalację pyinstaller
          .\installResources.ps1

      - name: Build executable
        run: |
          pyinstaller --onefile main.py  # Komenda do budowania pliku .exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: dist/main.exe  # Ścieżka do pliku .exe
