name: Build and Upload Executable

on:
  schedule:
    - cron: '0 0 * * 0'  # Uruchomienie automatyczne raz w tygodniu (niedziela o północy)
  push:
    branches:
      - Task1
      - Task2
      - Task3
      - Task4
      - Task5
      - Task6
      - Task7  # Uruchomienie po push na odpowiednie gałęzie
  workflow_dispatch:  # Ręczne uruchomienie przez użytkownika

jobs:
  build:
    runs-on: windows-latest  # Domyślny serwer Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Wybierz wersję Pythona

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller  
          .\installResources.ps1

      - name: List files in working directory
        run: dir

      - name: Build executable
        run: |
          if (Test-Path -Path ./Task1/main.py) {
            pyinstaller --onefile Task1/main.py
          } elseif (Test-Path -Path ./Task2/main.py) {
            pyinstaller --onefile Task2/main.py
          } elseif (Test-Path -Path ./Task3/main.py) {
            pyinstaller --onefile Task3/main.py
          } elseif (Test-Path -Path ./Task4/main.py) {
            pyinstaller --onefile Task4/main.py
          } elseif (Test-Path -Path ./Task5/main.py) {
            pyinstaller --onefile Task5/main.py
          } elseif (Test-Path -Path ./Task6/main.py) {
            pyinstaller --onefile Task6/main.py
          } elseif (Test-Path -Path ./Task7/main.py) {
            pyinstaller --onefile Task7/main.py
          } else {
            Write-Error "main.py not found in expected paths"
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: dist/*.exe  # Ścieżka do pliku .exe

